INSERT INTO publications (title, author, link) VALUES ('On squares of spaces and Fsigma-sets', 'Arnold W. Miller', 'http://arxiv.org/abs/math/0404421v1');
INSERT INTO publications (title, author, link) VALUES ('Generators and defining relations for the ring of differential operators  on a smooth affine algebraic variety', 'V. V. Bavula', 'http://arxiv.org/abs/math/0504475v1');
INSERT INTO publications (title, author, link) VALUES ('Some generalizations and unifications of $C_{K}(X)$, $C_ψ(X)$ and  $C_{\infty}(X)$', 'A. Taherifar', 'http://arxiv.org/abs/1210.6521v3');
INSERT INTO publications (title, author, link) VALUES ('The algebraic dimension of compact complex threefolds with vanishing  second Betti number', 'Frédéric Campana,Jean-Pierre Demailly,Thomas Peternell', 'http://arxiv.org/abs/math/9607215v1');
INSERT INTO publications (title, author, link) VALUES ('Projective space of a C*-module', 'E. Andruchow,G. Corach,D. Stojanoff', 'http://arxiv.org/abs/math/9911155v1');
INSERT INTO publications (title, author, link) VALUES ('A Remark on Soliton Equation of Mean Curvature Flow', 'L. Ma,Y. Yang', 'http://arxiv.org/abs/math/0312151v1');
INSERT INTO publications (title, author, link) VALUES ('Symmetry and Specializability in the continued fraction expansions of  some infinite products', 'James Mc Laughlin', 'http://arxiv.org/abs/math/0402459v1');
INSERT INTO publications (title, author, link) VALUES ('L''Application Canonique $J:H^2(X) \otimes H^2(X)-&gt;H^1(X\otimes X)$ n''est  pas Surjective en Général', 'Omran Kouba', 'http://arxiv.org/abs/math/0401335v1');
INSERT INTO publications (title, author, link) VALUES ('On the random nature of (prime) number distribution', 'Erika Alvarez,Jean Pestieau', 'http://arxiv.org/abs/math/0412288v1');
INSERT INTO publications (title, author, link) VALUES ('On the Lusternik-Schnirelmann category of spaces with 2-dimensional  fundamental group', 'A. Dranishnikov', 'http://arxiv.org/abs/0709.4018v1');
INSERT INTO publications (title, author, link) VALUES ('Discontinuity and Involutions on Countable Sets', 'Sung Soo Kim,Szymon Plewik', 'http://arxiv.org/abs/0705.2109v1');
INSERT INTO publications (title, author, link) VALUES ('Resolvability of spaces having small spread or extent', 'Istvan Juhasz,Lajos Soukup,Zoltan Szentmiklossy', 'http://arxiv.org/abs/math/0609091v1');
INSERT INTO publications (title, author, link) VALUES ('A Remark on the Assumptions of Bayes'' Theorem', 'Janne V. Kujala', 'http://arxiv.org/abs/1103.6136v1');
INSERT INTO publications (title, author, link) VALUES ('Sublinear Higson corona and Lipschitz extensions', 'M. Cencelj,J. Dydak,J. Smrekar,A. Vavpetic', 'http://arxiv.org/abs/math/0608686v1');
INSERT INTO publications (title, author, link) VALUES ('Cardinalities of weakly Lindelöf spaces with regular  $G_κ$-diagonals', 'Ivan S. Gotchev', 'http://arxiv.org/abs/1504.01785v1');
INSERT INTO publications (title, author, link) VALUES ('Verbal covering properties of topological spaces', 'Taras Banakh,Alex Ravsky', 'http://arxiv.org/abs/1503.04480v3');
INSERT INTO publications (title, author, link) VALUES ('New further integrability cases for the Riccati equation', 'M. K. Mak,T. Harko', 'http://arxiv.org/abs/1301.5720v2');
INSERT INTO publications (title, author, link) VALUES ('Diameter preserving linear bijections of $C(X)$', 'M. Gyory,Lajos Molnar', 'http://arxiv.org/abs/math/9707208v1');
INSERT INTO publications (title, author, link) VALUES ('Un théoréme de Nakai-Moishezon pour certaines classes de type (1,1)', 'Philippe Eyssidieux', 'http://arxiv.org/abs/math/9811065v1');
INSERT INTO publications (title, author, link) VALUES ('On Well-behaved Unbounded Representations of *-Algebras', 'Konrad Schmuedgen', 'http://arxiv.org/abs/math/0004163v1');
